language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cargo
    - os: osx
      osx_image: xcode12.2
      brew_packages: rust
    - os: osx
      osx_image: xcode10.1
      disable_homebrew: true
      r_check_args: ""
